server:
  grpc:
    addr: 0.0.0.0:7001
    timeout: 10
    version: v1.0.0
  serviceName:
    gateway

registrar:
  zookeeper:
    addr: ["localhost:2181"]
    namespace: "microservices"
    sessionTimeout: 15
